apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  APP_NAME: "Teste 12345" -- usar em base 64
  APP_VERSION: "5.0"  -- usar em base 64
  APP_AUTHOR: "Fernando5"  -- usar em base 64